# tic documentation: https://docs.ropensci.org/tic/dev/

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes', type = 'binary')"
  - cmd: Rscript -e "if (getRversion() < '3.2' && !requireNamespace('curl')) install.packages('curl', type = 'binary')"
  - cmd: Rscript -e "options(pkgType = 'binary'); remotes::install_github('ropensci/tic', upgrade = 'always'); print(tic::dsl_load()); tic::prepare_all_stages()"

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# no testing on R-devel because no package binaries are available
environment:
  matrix:
    - R_VERSION: release
    - R_VERSION: oldrel
  id_rsa:
    secure: JgXH0fSjTJCXa8iGR+8U03XbhNjUtcS7asbxTIwQJi8aVT+0Ffgo1wRPPASYayTy99KQWduqKek5AU5tOGA2nw2up4t0bAJSoHjxvEw0HJTlgLum8Dnxvz5iGqCmujbaoBZbej8vqfV4jbZbYdXpvWsd7A+9YTwdGggYrUwpoLRHT3JkG1l1c3O2gA0Txir7qNQocvBGETLQJ90QfYp2MwX9k3s859Q1G+5kLQgrCLfjfhGoUTKRSrB1Av75L3LFWkYT+yOucGl+5uH8xG5mM/AwIVfk5nzzoIaP4kACh1E05QLRUG3Rtmn4serBZY9++PpWjg4q62fnZqQUqKTY6tmC7c40sLDRGl5zdQClkhVwiljtyHMJSiN0VJ4TfVO3oqm4laWCNAFFOs4kVejuSAKTFUTKJTlO6M+HU2g5sdhv8ZuotU9iP0eNVQLi1viiSOsiKoZrpUYkP0ynIaqie5fsvdnEnhw+PWCiEBqpDMvEeIhfl04Iuc2NcMug7iwVwzUnCbeY/268arwv4nXXk2XsWvsHQkKQuLLVD0o2LWQz1NT6Essfqa34L+6hz4kHKUeWVvwSqKSDvR0pAaving1q448QE3lozxLMX9alhaEcLRb+3pnyvZiVj7PfeYoZXnsXXGRIL7GPHrTFmrQThghsIsLySMIbmm+rBRAjapbhXUKQswfY4o7UPVWqKXdNTN+VAlRQbi2saTxgd0zj9RrbFruISWFBoFlwk7plX87n95U7qBDBiqoARHEJz6ShYkcRwzYTTMxyZ5MiO9pYUO5ssdTtI9V0Qy7lXnvSGs5laEZY68cVzTL/RjLIeHV7iUN7itcpLf5Umo8HPxwCE8NJDI/ULKBqKih839jmhBHxdXQr3CgGDAGok9WArBnzJgDzPN2cn3QFBTMEwP0YYo4sFD88y8QQlJaRotSPa3S45+e8VRL0jG4Z0SX0NIH//TSHAhuTXOjZ7eqhtCqrnP0hnuyJDfZdJZ+g0rMz6uhSF7Z8m8HZ72sbiTu2q3fk637RtWUUw4zyBhwKBBMD3R5lh2eunFJCW/zD1WOcwj2LfME6TDk7/hXlQc1NT3m8CO2od2waaSlkQh4x7w9+hrm3ZxtbBP7+ihS2ouGm5pnmv9/BS5FUiXGotQuB0RS4CsCFn8lF9gNl0HqkgbPA/hS9Zu74aCafvLNGpAFqdvScIelYWrUdIgvhLSxEJWP+/nyoNWuV8vVRHeNjWzX1/1+hYWca973XMAHV00dmpPd8TT95xvHusAFchF5CJCzrVibkte1heUv9A7ALOmF6CNNnVvopPclNpmomKWmZ01zN1iZFssaME8hz6yvv9DNbpeQqVu1K3VIzeLJ6kjbV4rKqeTWU87r9OVPZ4PBd/WM0JSxcT6I8mItFGVv5AE0cyTiGqB/1AJ5z9Y0/8yasx2/+aRMLKuDswtk90vWxmuo4VRasdIfVJWkJ8dZ3oqcBsGLuCPCxMRh2R9YimK1SM1iYS6Ujkv6oQyBMRbjEP2U11anGBknb3WeWBNxnSa2GvTpkSwZQpkaQ9kiRv8VUbLTg0tPubEYY+0iupIKnSZuFxK3BvVfaoenromyRtdgMxL7aTaSNdeAGE0Igzfz9TfPdR9dueMp7gfegjMV09EZ6iWB4i5viEQEuqAC22D+O61JxNxy/9nfPfVljv3Ep633VwppLYjl0D+R6MCISZIlR/Y9WQAawRdfeJn2d/quUiZW2DI+nkiUAyDEj/CoW9JnXmjylmnXPzIYdnsAsk9S4Hk7fAXeODH4A5r/b6k9A/PhPVzb3pSsem4gU7u1Wch7Ib0+yCkqcueXk/Nq+tM2mbJpqS7w5gaRQMJeQvcjGJXv3FDvrxj1xhMrqbwKb8fgvb7qGYfcdwm0xMlSNaPv/kAaMIJ09HlUMcLCE3Atvr2O6Y5L0UILf9Bp//cafAnyL832qPAkQglF3uiofAD9QOjIj0sD7yTLz2MAlX8odF6HLMZU6p3eERtrF+Vsb3iMXKx6r9WZu3cS9M/5blySbW1Z9SNg9VDegN7bxNmB92N+PSnp5tvyderoHPof7PJHDLItvmTwSfL4GlGY536OWDhiofB7ZzT8py9HRH+4aqt4eOfb3YVBClh7qQLrP2F2dBHNpiorppDDYCIy2j/EEkwSmR8qEQ7ZedwOqne7AR6NF3lDOyMsDsa3js7x/6g3h2clVL7FtNwVJG+xS874a0TS1/CaMs/8Oxo4cRkCZBHQBQCp7p0lMOU29AoLBBCAha+dGUqUvyN1rw7im0irhTusUYTexMpXMubfiZ7G615QLkucAcBs90QtF4JjJQ/Tv7P88F4Hjiro+3kigMU8fvteujh2FvwRTPICSSMohAzjW6wI1QOuzK6cnHNQQb4Z2p9OGp1XB+SL9dEN8A2wLJQW4CMerZC4tgO2LoQ5WkAOf87niirIQGG7fH1pZmHpzScfOqcHdFTo62pl4OaTlUJeyHSSzxSJlLwVUsNi1z8bRXKzZtqrbpmATr0rmfh2ksepGcRhDPv9fdipIUj06ED/lMlm/t12AvnnbDFbN8ZvcymZtnz890KWNs3iqx6sya3Vwi7crIB4KBMMbI5HU+uBa0i4Awj5uP9S7iEEO6cSk+VmZylCoxy9yV4fuMaAfd4cORZxo++cERHdeWBZ770OsuDgl/PsAeKl0I8yXnIV37Tz3Tt0DufnDypd3Ijtewj9cBRdN37ITbtJI3AeH3HprAHVgBxyXMGwNTjnOpuSmru37Kz+SFIK2wyDbyJstN9SF+CfN92dyY6nssAtymVf2oTQiwlOWdo5E+aJAyuwJREOrpf5sjWylJ1MCGaoBkj3F9yiYcLx8+EjEgZpoBXU6pRWluYHZxzv+MyRG6oJDwTYIviiOe2BkAWte2i60k353PLXyfuvWw/DrAiD0ZlWe/sw+/oPmYvOWuD47TsOBHrw1eifv7ZOsZd+JamBTPinPXEYj7ASUKIl3Qsenp0rbE41R9j7Q6tXc3VqxALK6zbssIsbhU3FTJx4GEERUuhFD5Jss08lgqDgVKHA=
  USE_RTOOLS: true

matrix:
  fast_finish: true
# Custom user code -------------------------------------------------------------
