# tic documentation: https://docs.ropensci.org/tic/dev/

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes', type = 'binary')"
  - cmd: Rscript -e "if (getRversion() < '3.2' && !requireNamespace('curl')) install.packages('curl', type = 'binary')"
  - cmd: Rscript -e "options(pkgType = 'binary'); remotes::install_github('ropensci/tic@do-drat', upgrade = 'always'); print(tic::dsl_load()); tic::prepare_all_stages()"

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# no testing on R-devel because no package binaries are available
environment:
  matrix:
    - R_VERSION: release
    - R_VERSION: oldrel
  GITHUB_PAT:
    secure: VXO22OHLkl4YhVIomSMwCZyOTx03Xf2WICaVng9xH7gISlAg8a+qrt1DtFtk8sK5
  id_rsa:
    secure: NrU0oteWTTGWQ1MwYmHI8A5P2JaOgqlASL6Nuva4CVGPnktFqi+A4sviIlezrv4wApJ5CLg8r2/DUCMcqXhYhWWSB1mz70O7ZnObsc5qWTQCRaWlJd3rkY+OTQqKI4SpazHLOo/lRrUXTzhSm7sdhqBm7zWNBAKecjHQnanw9ivK3jThhvuF1umwx46D1zup6CBxI3pKSvYdjtWkn2U0NiCDxHcc52vHg6ab8+14atycbBC6ktm6HiZWNJxgU7zvO/Bio98OZ/T0mi/uoQmzxihTjBos03sWLOMAhOBhySO+9s8cBZNPrCXyJAGb8fVVSnPDbd/88BxYwdEiAPt5tu8NNviXZKmdX6q97mIuAdu+fjzi6STlNlRQZ9C1dB0tC+NDzoywyreYzW5+bFZpm7hMOFZfC++Z+aThtmBbRzKevRbIqRotuBqNQ5fxbxNeFh1pNGnWIiMJnBG16vsfNe9SnMjG6keBDKh7WrLpEAiBwOd7aMVCN9XXIbtqU5Cd/weromwWw5nRNP0d9lbF/x2tVlMQGp65vBsIgXS3lcuR20aXU1zsdSSEzdugItIuqvma94Ajcj9IDcluCkZBBjHdVMDx3160F4qcCePT5mf+qO7eF+FXXO7wK0FsQWAvP/XTrsaVyQCA3jGwe/6f80i7Y1QY//JvEndz0n9PYooAQFfm70lvdKzmvDAyNLwpSgG8+3AXA8pjhLMb/zgZsGGAX1P6FYTFjAGDS1NwQPsagSKUVgA9RIsR+m7Te25mFUPTCTD9v84IcBtOipO04oYY8jL8+3qxTZcDghC0+Y9dLXSUGglPuDczQrRY2DBy404z44uYBcgNKIph5apMd2DKEwCMWlSNn6roiSKjMPP2Syk8e/LPzYnhbYsOltcakPWlvESDJ+yq2CYHsyPQ3aNAQKhva/yCsGFXjiXwoZiLKo5bsu3Qefz8+6CAZX5Rs3Rc+uqi+2/+1zGOn5h10Y82+SlrmvM98w/NfjZuABZNcN4W8fq7r8RR9FAqOsnPpJdhloRpzmN4IHaa2qfskoASuJ+jwU5OmUZ7ksK3CC2+Ksq3oQV/Mm3714GBxLFD39FIRhd40VtDHLGn8VBXlhqTl/gOB8HM7muJT+0J9ezcwH9bkgtYGFhSVuXmqbaTC3Rjp2HnyZoLMwZnov9ZFCR2LhMMWVMn5CxraluvNhESEnH7TpDDnzMRm8YjD5BhThPoxCNp4lyREdUUxMkyGxH7pub9UqqXCnrNt6RF3ikWH0mXA2DlCVTQHgJxM+vbvljJxZPs08gVDAZu7rIw0AjDioDV+9D9Zzrd9HSxpzLwiH3jxU9PXEef+SrrWnrDjEuZib/52pVEwBWpMxNHPMNS08g5lq0N9SW1yWEu3nClDG9x2PbOLmcr6/DkFcbo71pVjfRxpKy4xohJel7AalpScBG+Jsj66XuAgdXJkHzBPcQmYCkf0xF/tmwa1iU/O/WKHBNDT6gwFOR8ItDKxP8ucqCTLQpTZ3vh00+bRirp9RIW/csF2YwlrndZteP8XVM5OlWmX1sifpBhlQ4nm+pUFT94QrlgOEL4CeGLTB1BucwMe49AiWHG+Wx/D8Eq7vhxSNQXmJJX6Q+gc6BasAlXCuQE3zO+eXYZ1s4fWUsoJY5tvsLyP4IbT9qY8+lyaF9kWucnvsJQqC2rxRtQS3lsXlXv75uO1TEv1X05dV3SAMXFvZaa3k0E+karyX1TXgLlJP9qXnCb0ByGyW9z8BnfxQXGzFncBzYXfYMQuh+uDn31aictya6kbX32gliHFEd6EzDSVtOxQQdeSFEowXS9PcKfJ0CbfzWZ/bcgRDIzuEftRfTD/JCNg1jB+8rTwpM/R1KNnEKHEbPgcK2xe4ct4Ak2MVHew6+ngmZNSlrbauCc7eg8BYsvkvygfQoun3W/847+koZqlVPcnN7a/IWvMDfivUkMpEMbHBRsXPf3RXGYSMeQOgKZs5HSpAQTHgMP0JAtpL26VqI6RfZpiYI1Nugdh2H7tLaYB5Poq7yesZ2194rZM8NFXi5eo4Tuxqyb2MriRLcJKHMQBQ1gt7k4fwDuSMDKF6lNNGdZvRvkPZRs8458ZGnJbwxlYrHo6Myf/DjKdjUb/3tiIwETIW8qPdZdWwJvUFqZKe5Jp/kzBAHURXjhqXjpzcAFQtmFNv5SQATv5Ghl5cWDIa102HYuj15ZkuMNa4F98tpVDebCvfGZm0V101KDj/V9qmsRREBiHjdJZYklijtPn5rYUZ/keaUwkeQga7ChWhsfdBxE48/oRssTHOl9vRn8FRbekPpkG/oE5Jnuw43i/FtSEo8maEqy3wKPeZ9At8LyIzkZUiTVJOd1flsZWP3Xvcg71YGIZMVZk64Uq4wY7IxWdsewT2kZEyGiRNUuKT1Wq6Kkq8yGguqMfrjjBR5uHWhceoAvDMyXp3IUCeVRY1q3eABsBl5lwJD0dmqWdfLhhywOeY0RHgr/otZNvZ8WgJuJlvSIqomkldwOIpffCRCSnh//9IkDrBL1MGCdgq8B5Je6Immbx+cFShPHuqYBXKQ6oqdKecRDbxjpck60iLYChYYfZk+aI04HtXSYyu5ptOajP00/q4EFz16RuSyQ9ZJzfKaCmC3+qla7itxjHNP50LV5JLrrUkpprMtoTFiNEYJHDASORwYbq4mubAiuzvxmH0xKopZIwkpKYyovoss0CahaOzvE7rC7flNj5yVkfj+h6GgztjqsoDkKyS87BsNKdWeNQOzsFm1XWG1KNowQxvJ64pgkkCSi/6z+YU8ay+sbnsMyDKWqTnkHR6DVoUKAvrxw7L4vQjHhJ43tE8gmE8/XPqipXnkmLUN8YftiKglzo9PeL3O3ep9fFIat2h52m2SeCF1etRlh3EW7965+RDdQaWqVAx/wOegg2eLFImc5PvPLIzy0KL1m2DIonNcCWM0a3lS9arIUDvdxFDnjFwtlSr6wRceuH+FKpLogiroU6Dvf3XIDvw1T+Gqfn3JxrPyNGACQxszrEmA9sNr1Qs6wH5+Ben0+AM8bEnhwecE=
  USE_RTOOLS: true

matrix:
  fast_finish: true
# Custom user code -------------------------------------------------------------
